import test from 'node:test';
import {existsSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createApp} from '../server/index.js';
import {hashPin,verifyPin,verifyMicrosoftIdentity} from '../server/auth.js';
import {calculate} from '../server/domain.js';
import {importLegacy} from '../server/import-legacy.js';
import {generateKeyPair,SignJWT} from 'jose';
const template={id:'t',name:'Test template',roleId:'r',status:'active',method:'leadlag',leadWeight:40,objectives:[{id:'o',name:'Approved fixture',weight:100,strategicIds:[],criteria:[{id:'lead',name:'Lead fixture',group:'lead',weight:1,status:'active',direction:'higher',target:100,unit:'%',definition:'Test only'},{id:'lag',name:'Lag fixture',group:'lag',weight:1,status:'active',direction:'lower',target:10,unit:'units',definition:'Test only'}]}]};
const values={lead:{actual:80,na:false,evidence:'fixture'},lag:{actual:20,na:false,evidence:'fixture'}};
async function fixture(t){const app=createApp({dbPath:':memory:',origin:'http://localhost:3000'});const s=app.store;s.save('roles',{id:'r',name:'Test role'});s.save('departments',{id:'d',name:'Test department'});s.save('templates',template);for(const [id,role,managerId] of [['admin','ADMIN',''],['manager','CHEFIA',''],['employee','COLABORADOR','manager'],['other','COLABORADOR',''],['outsider','CHEFIA',''],['direction','DIRECAO','']]){s.save('users',{id,name:id,username:id,role,active:true,roleId:'r',departmentId:'d',managerId,oid:''});s.db.prepare('INSERT INTO credentials(user_id,hash,must_change) VALUES(?,?,0)').run(id,await hashPin('91827463'));}
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${app.server.address().port}`;t.after(async()=>{await new Promise(resolve=>app.server.close(resolve));s.db.close();});
const client=()=>{let cookie='',csrf='';return {async request(path,method='GET',body,extras={}){const r=await fetch(base+'/api'+path,{method,headers:{Origin:'http://localhost:3000',...(body?{'Content-Type':'application/json'}:{}),Cookie:cookie,'X-CSRF-Token':csrf,...extras},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();if(data.csrf)csrf=data.csrf;return {status:r.status,data};},async login(user,pin='91827463'){return this.request('/login','POST',{username:user,pin});}};};return {...app,client,base};}
test('attainment keeps pending/N/A; lower and zero targets do not divide by zero',()=>{assert.equal(calculate(template,values).score,62);const copy=structuredClone(template);copy.objectives[0].criteria[1].status='definition';assert.equal(calculate(copy,values).score,null);assert.equal(calculate(template,{...values,lag:{na:true,reason:'no eligible cases'}}).score,null);copy.objectives[0].criteria[1]={...copy.objectives[0].criteria[1],status:'active',direction:'zero',target:0};assert.equal(calculate(copy,{...values,lag:{actual:0,na:false}}).score,92);assert.equal(calculate(copy,{...values,lag:{actual:1,na:false}}).score,32);});
test('PIN hash and verification',async()=>{const h=await hashPin('91827463');const passwordHash=await hashPin('Uma palavra-passe longa!');assert(await verifyPin('Uma palavra-passe longa!',passwordHash));assert(!await verifyPin('outra palavra-passe',passwordHash));assert(!h.includes('91827463'));assert(await verifyPin('91827463',h));assert(!await verifyPin('00000000',h));await assert.rejects(hashPin('1234'));});
test('Microsoft verifies signature, issuer, audience, tenant, nonce and expiration',async()=>{const {publicKey,privateKey}=await generateKeyPair('RS256');const config={tenantId:'tenant',clientId:'client',nonce:'nonce'};const sign=(overrides={})=>new SignJWT({tid:'tenant',oid:'user-id',nonce:'nonce',...overrides}).setProtectedHeader({alg:'RS256'}).setIssuer('https://login.microsoftonline.com/tenant/v2.0').setAudience('client').setSubject('user-id').setIssuedAt().setExpirationTime('5m').sign(privateKey);assert.equal((await verifyMicrosoftIdentity(await sign(),publicKey,config)).oid,'user-id');for(const change of [{nonce:'other'},{tid:'other'}])await assert.rejects(verifyMicrosoftIdentity(await sign(change),publicKey,config));await assert.rejects(verifyMicrosoftIdentity(await sign(),publicKey,{...config,clientId:'wrong'}));await assert.rejects(verifyMicrosoftIdentity(await sign(),publicKey,{...config,tenantId:'wrong'}));const expired=await new SignJWT({tid:'tenant',oid:'user',nonce:'nonce'}).setProtectedHeader({alg:'RS256'}).setIssuer('https://login.microsoftonline.com/tenant/v2.0').setAudience('client').setSubject('user-id').setIssuedAt().setExpirationTime(1).sign(privateKey);await assert.rejects(verifyMicrosoftIdentity(expired,publicKey,config));const other=await generateKeyPair('RS256');await assert.rejects(verifyMicrosoftIdentity(await sign(),other.publicKey,config));});
test('server permissions, publication, immutable snapshots and acknowledgement',async t=>{const f=await fixture(t),a=f.client(),m=f.client(),e=f.client(),o=f.client(),x=f.client(),d=f.client();await Promise.all([a.login('admin'),m.login('manager'),e.login('employee'),o.login('other'),x.login('outsider'),d.login('direction')]);const anon=f.client();assert.equal((await anon.request('/catalog')).status,401);assert.equal((await e.request('/catalog/users','POST',{name:'escalate'})).status,403);assert.equal((await x.request('/evaluations','POST',{employeeId:'employee',templateId:'t',period:'2026-Q1'})).status,403);
let ev=(await m.request('/evaluations','POST',{employeeId:'employee',templateId:'t',period:'2026-Q1'})).data;assert(ev.id);assert.equal((await e.request('/evaluations/'+ev.id)).status,404);assert.equal((await d.request('/evaluations/'+ev.id)).status,404);assert.equal((await e.request('/self-assessments')).data[0].results,undefined);assert.equal((await e.request('/self-assessments')).data[0].comment,undefined);ev=(await e.request(`/evaluations/${ev.id}/self`,'POST',{expectedVersion:ev.version,results:values})).data;
assert.equal((await m.request('/evaluations/'+ev.id,'PUT',{expectedVersion:1,results:values,comment:'',improvementPlan:''})).status,409);ev=(await m.request('/evaluations/'+ev.id,'PUT',{expectedVersion:ev.version,results:values,comment:'Reviewed',improvementPlan:'Train'})).data;assert.equal(ev.calculation.score,62);
const latest=f.store.get('templates','t');const edited=structuredClone(latest);edited.status='definition';edited.objectives[0].criteria[1].target=100;const changed=await a.request('/catalog/templates/t','PUT',{...edited,expectedVersion:latest.version});assert.equal(changed.status,200);assert.equal((await m.request('/evaluations/'+ev.id)).data.template.objectives[0].criteria[1].target,10);
for(const state of ['evaluation','validation']){ev=(await m.request(`/evaluations/${ev.id}/transition`,'POST',{expectedVersion:ev.version,state})).data;}assert.equal((await m.request(`/evaluations/${ev.id}/transition`,'POST',{expectedVersion:ev.version,state:'approved'})).status,403);assert.equal((await m.request('/evaluations/'+ev.id,'PUT',{expectedVersion:ev.version,results:values,comment:'alter',improvementPlan:''})).status,400);for(const state of ['approved','published'])ev=(await a.request(`/evaluations/${ev.id}/transition`,'POST',{expectedVersion:ev.version,state})).data;
assert.equal((await e.request('/evaluations/'+ev.id)).status,200);assert.equal((await o.request('/evaluations/'+ev.id)).status,404);assert.equal((await x.request('/evaluations/'+ev.id)).status,404);assert.equal((await d.request('/evaluations/'+ev.id)).status,404);assert.equal((await o.request(`/evaluations/${ev.id}/acknowledge`,'POST',{expectedVersion:ev.version,comment:''})).status,403);ev=(await e.request(`/evaluations/${ev.id}/acknowledge`,'POST',{expectedVersion:ev.version,comment:'Read, but disagree'})).data;assert(ev.acknowledgement);assert.equal((await e.request(`/evaluations/${ev.id}/acknowledge`,'POST',{expectedVersion:ev.version,comment:''})).status,409);assert.equal((await a.request('/catalog/roles','POST',{name:'blocked'},{Origin:'https://other.example'})).status,403);assert.equal((await a.request('/catalog/roles','POST',{name:'blocked'},{'X-CSRF-Token':'wrong'})).status,403);assert.throws(()=>f.store.db.prepare("UPDATE entities SET body='{}'").run());assert.throws(()=>f.store.db.prepare("DELETE FROM audit").run());});
test('pending rules block publication; PIN reset invalidates sessions and forces change',async t=>{const f=await fixture(t),a=f.client(),m=f.client(),e=f.client();await a.login('admin');await m.login('manager');await e.login('employee');let ev=(await m.request('/evaluations','POST',{employeeId:'employee',templateId:'t',period:'2026-Q2'})).data;for(const state of ['evaluation','validation'])ev=(await m.request(`/evaluations/${ev.id}/transition`,'POST',{expectedVersion:ev.version,state})).data;assert.equal((await a.request(`/evaluations/${ev.id}/transition`,'POST',{expectedVersion:ev.version,state:'approved'})).status,400);await a.request('/users/employee/pin','POST',{pin:'82736491'});assert.equal((await e.request('/me')).status,401);await e.login('employee','82736491');assert.equal((await e.request('/catalog')).status,403);assert.equal((await e.request('/pin','POST',{pin:'73645182',currentPin:'82736491'})).status,200);assert.equal((await e.request('/catalog')).status,200);});
test('login lockout, self profile tampering and static legacy files inaccessible',async t=>{const f=await fixture(t),c=f.client();for(let i=0;i<5;i++)assert.equal((await c.login('employee','00000000')).status,401);assert.equal((await c.login('employee')).status,401);assert.equal((await fetch(f.base+'/config.js')).status,404);assert.equal((await fetch(f.base+'/../server/auth.js')).status,404);const a=f.client();await a.login('admin');const u=f.store.get('users','employee');await a.request('/catalog/users/employee','PUT',{...u,active:false,expectedVersion:u.version});assert.equal((await c.login('employee')).status,401);});
test('legacy import is atomic, idempotent, unpublished and preserves historical weights and competencies without plaintext PIN',async t=>{const f=await fixture(t);const data={UtilizadoresDashboard:[{id:'1',fields:{NumeroColaborador:10,NomeColaborador:'Historic Employee',Funcao:'Historic role',PIN:'1234',TipoUtilizador:'COLABORADOR'}}],ConfiguracaoFuncoes:[{fields:{NomeFuncao:'Historic role',TipoConfiguracao:'KPI',NomeReferencia:'K',Peso:99,Ativo:true}}],HistoricoKPIs:[{id:'k1',fields:{ColaboradorID:10,AvaliacaoID:'old1',NomeKPI:'K',ValorAtual:80,PesoKPI:25,Meta:75,SnapshotOficial:true,DataAtualizacao:'2025-12-31T12:00:00Z'}},{id:'k2',fields:{ColaboradorID:10,AvaliacaoID:'old1',NomeKPI:'L',ValorAtual:40,PesoKPI:75,SnapshotOficial:true,DataAtualizacao:'2025-12-31T12:00:00Z'}}],HistoricoSoftSkills:[{id:'s1',fields:{ColaboradorID:10,AvaliacaoID:'old1',NomeSkill:'Skill',ValorAtual:90,PesoSkill:10,SnapshotOficial:true}}]};assert.equal(importLegacy(f.store,data).imported,1);const ev=f.store.list('evaluations')[0];assert.equal(ev.state,'draft');assert.equal(ev.calculation.score,50);assert.equal(ev.calculation.skills[0].score,90);assert.equal(ev.template.objectives[0].criteria[0].weight,25);assert.equal(importLegacy(f.store,data).imported,0);assert(!f.store.db.prepare('SELECT body FROM entities').all().some(r=>r.body.includes('"PIN"')));const invalid=structuredClone(data);invalid.HistoricoKPIs[0].fields.PesoKPI=null;invalid.HistoricoKPIs.forEach(r=>r.fields.AvaliacaoID='other');assert.throws(()=>importLegacy(f.store,invalid));assert.equal(f.store.list('evaluations').length,1);});
test('BSC department access, target snapshots and lifecycle; approved definitions must be validated again',async t=>{const f=await fixture(t),a=f.client(),m=f.client(),d=f.client();await a.login('admin');await m.login('manager');await d.login('direction');f.store.save('objectives',{id:'corp',name:'Corporate fixture',scope:'corporate',status:'active'});f.store.save('objectives',{id:'dept',name:'Department fixture',scope:'department',departmentId:'d',parentId:'corp',status:'active'});f.store.save('kpis',{id:'k',name:'Fixture KPI',objectiveId:'dept',status:'active',direction:'higher',target:10,unit:'units',definition:'Fixture definition'});f.store.save('kpis',{id:'corp-k',name:'Corporate KPI',objectiveId:'corp',status:'active',direction:'higher',target:10,unit:'units',definition:'Fixture definition'});
let r=await m.request('/bsc-results','POST',{kpiId:'k',period:'2026-Q1',result:{actual:9,na:false,evidence:'fixture'}});assert.equal(r.status,200);assert.equal((await m.request('/bsc-results','POST',{kpiId:'corp-k',period:'2026-Q1',result:{actual:9,na:false}})).status,403);assert.equal((await d.request('/bsc-results','POST',{kpiId:'k',period:'2026-Q1',result:{actual:9,na:false}})).status,403);
const k=f.store.get('kpis','k');assert.equal((await a.request('/catalog/kpis/k','PUT',{...k,target:20,expectedVersion:k.version})).status,400);let current=(await a.request('/catalog/kpis/k','PUT',{...k,status:'definition',target:20,expectedVersion:k.version})).data;for(const status of ['validation','approved','active']){const response=await a.request('/catalog/kpis/k','PUT',{...current,status,expectedVersion:current.version});assert.equal(response.status,200);current=response.data;}assert.equal((await m.request('/bsc-results','GET')).data[0].kpi.target,10);r=await m.request('/bsc-results','POST',{kpiId:'k',period:'2026-Q1',expectedVersion:r.data.version,result:{actual:8,na:false}});assert.equal(r.data.kpi.target,10);assert.equal((await m.request('/bsc-results','POST',{kpiId:'k',period:'2026-Q2',result:{actual:18,na:false}})).data.kpi.target,20);});
test('private seed contains exactly the supplied objectives and role proposals, all inactive',{skip:!existsSync('docs/private-catalog.json')},async()=>{const {openStore}=await import('../server/store.js');const {seed}=await import('../server/bootstrap.js');const {validateTemplate}=await import('../server/domain.js');const s=openStore(':memory:');seed(s,'docs/private-catalog.json');assert.equal(s.list('objectives').length,12);assert.equal(s.list('templates').length,4);assert.equal(s.list('templates').reduce((n,t)=>n+t.objectives.length,0),20);assert.equal(s.list('users').length,0);for(const t of s.list('templates')){validateTemplate(t);assert.equal(t.status,'definition');for(const c of t.objectives.flatMap(o=>o.criteria))assert.equal(c.status,'definition');}assert.equal(s.get('templates','template-V').objectives[0].criteria[2].target,1.5);assert(s.list('kpis').every(k=>k.status==='definition'&&k.target===null));s.db.close();});
